# @format

useTabs: true
semi: true
singleQuote: true
quoteProps: 'as-needed'
trailingComma: 'none'
bracketSpacing: true
jsxBracketSameLine: false
jsxSingleQuote: true
arrowParens: 'avoid'
insertPragma: true
endOfLine: 'lf'
printWidth: 120
